# Generated by Django 5.2.4 on 2025-07-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='dimensions_length',
            new_name='length_dimensions',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='dimensions_width',
            new_name='width_dimensions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date when order was completed', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Date when customer confirmed the order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_company',
            field=models.CharField(blank=True, help_text='Optional: company name of the customer placing the order', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_at',
            field=models.DateTimeField(blank=True, help_text='Date when estimation was provided', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='additional_files',
            field=models.FileField(blank=True, help_text='Additional files from customer', null=True, upload_to='design_files/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='height_dimensions',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height of the design in centimeters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='needs_custom_design',
            field=models.BooleanField(default=False, help_text='Indicates if this item needs custom design service'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='requested_color',
            field=models.CharField(blank=True, help_text='Color requested by customer', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='requested_finish',
            field=models.CharField(blank=True, help_text='Finish requested by customer', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='requested_material',
            field=models.CharField(blank=True, help_text='Material requested by customer', max_length=100),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='is_base_service',
            field=models.BooleanField(default=False, help_text='Indicates if this is one of the 5 base services'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_name',
            field=models.CharField(default='AGAH Solutions', help_text='AGAH Solutions', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='personalized_design_price',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Base price for personalized design service (can be adjusted per order)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_completion_date_days',
            field=models.IntegerField(blank=True, help_text='Estimated completion time in days', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='design_file',
            field=models.FileField(blank=True, help_text='Design file for the order item', null=True, upload_to='design_files/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(help_text='Type of service requested', on_delete=django.db.models.deletion.CASCADE, to='services.typeservice'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price for the service type', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the service type'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description of the service type', max_length=200),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='type',
            field=models.CharField(choices=[('plasma', 'Plasma Cutting'), ('laser_engraving', 'Laser Engraving'), ('laser_cutting', 'Laser Cutting'), ('3D_printing', '3D Printing'), ('resin_printing', 'Resin Printing'), ('cnc_milling', 'CNC Milling'), ('vinyl_cutting', 'Vinyl Cutting'), ('custom_design', 'Custom Design'), ('assembly_service', 'Assembly Service')], help_text='Type of service offered', max_length=50, unique=True),
        ),
    ]
