# Generated by Django 5.2.4 on 2025-08-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
    ]
