# Generated by Django 5.2.4 on 2025-07-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_dimensions_length_orderitem_length_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconfiguration',
            name='personalized_design_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='additional_files',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='requested_color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='requested_finish',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='requested_material',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_design_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for custom design service for this specific item', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='order_display',
            field=models.IntegerField(default=0, help_text='Order display for the service type (auto-assigned)'),
        ),
    ]
