# Generated by Django 5.2.4 on 2025-08-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20250814_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfiguration',
            name='company_tagline',
            field=models.CharField(default='Cutting-Edge Solutions, Crafted to Perfection', help_text='Tagline principal que aparece en la página de inicio', max_length=200),
        ),
        migrations.AddField(
            model_name='companyconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companyconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark this service as featured to highlight it in the frontend'),
        ),
    ]
