# Generated by Django 5.2.4 on 2025-07-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_companyconfiguration_personalized_design_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeservice',
            name='type',
            field=models.CharField(blank=True, help_text='Type of service offered (auto-generated from name)', max_length=50, unique=True),
        ),
    ]
