# Generated by Django 5.2.4 on 2025-09-03 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_companyconfiguration_company_tagline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyconfiguration',
            options={'verbose_name': 'Company Configuration', 'verbose_name_plural': 'Company Configuration'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='principal_image',
        ),
        migrations.AddField(
            model_name='typeservice',
            name='image',
            field=models.ImageField(blank=True, help_text='Service image for display', null=True, upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='about_us',
            field=models.TextField(blank=True, help_text='About us section content'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_address',
            field=models.TextField(blank=True, help_text='Company address'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_name',
            field=models.CharField(default='AGAH Solutions', help_text='Name of the company', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_phone',
            field=models.CharField(default='+52 665 127 0811', help_text='Main phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_tagline',
            field=models.CharField(default='Cutting-Edge Solutions, Crafted to Perfection', help_text='Company tagline or slogan', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_time_response_hours',
            field=models.IntegerField(default=24, help_text='Expected response time in hours'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='contact_email',
            field=models.EmailField(default='agahsolutions@gmail.com', help_text='Main contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 3, 23, 29, 53, 422224, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(help_text="Customer's email address", max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(help_text="Customer's full name", max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, help_text="Customer's phone number", max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Unique order number (auto-generated)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('estimated', 'Estimado'), ('confirmed', 'Confirmado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('canceled', 'Cancelado')], default='pending', help_text='Current state of the order', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description for the service'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='design_file',
            field=models.FileField(blank=True, help_text='Upload design files for the order', null=True, upload_to='order_files/'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='laser_cutting_time',
            field=models.IntegerField(blank=True, default=10, help_text='Cutting/Engraving time in minutes (minimum 10)', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='laser_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Material cost', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of the service the consumer wants'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates if the service is active'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price for the service', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured services appear prominently'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='order_display',
            field=models.IntegerField(blank=True, help_text='Order for displaying services (auto-assigned)', null=True),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description of the service', max_length=200),
        ),
    ]
