# Generated by Django 5.2.4 on 2025-09-04 21:28

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_companyconfiguration_options_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyconfiguration',
            options={'verbose_name': 'Company Configuration', 'verbose_name_plural': 'Company Configurations'},
        ),
        migrations.AlterModelOptions(
            name='typeservice',
            options={'ordering': ['order_display', 'name'], 'verbose_name': 'Type Service', 'verbose_name_plural': 'Type Services'},
        ),
        migrations.RemoveField(
            model_name='companyconfiguration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='companyconfiguration',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_consumables',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_design_programming_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_material_cost',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_material_used',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_post_process_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_time',
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='active',
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='is_base_service',
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='laser_material_area_used',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total material area used in square inches', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='laser_setup_time',
            field=models.IntegerField(blank=True, default=10, help_text='Setup time in minutes (minimum 10)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plasma_material_area_used',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total material area used in square inches', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plasma_setup_time',
            field=models.IntegerField(blank=True, default=15, help_text='Setup time in minutes (minimum 15)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_3d_consumables',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Cost of consumables (supports, etc.)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_3d_design_programming_time',
            field=models.IntegerField(blank=True, default=30, help_text='Design and programming time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_3d_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Material cost per gram', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_3d_material_used',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total material used in grams', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_3d_post_process_time',
            field=models.IntegerField(blank=True, default=10, help_text='Post-processing time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_3d_printing_time',
            field=models.IntegerField(blank=True, default=120, help_text='3D printing time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_3d_setup_time',
            field=models.IntegerField(blank=True, default=20, help_text='Setup time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='resin_consumables',
            field=models.DecimalField(blank=True, decimal_places=2, default=2.0, help_text='Cost of consumables (washing solution, FEP film, etc.)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='resin_design_programming_time',
            field=models.IntegerField(blank=True, default=25, help_text='Design and programming time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='resin_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Resin cost per ml', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='resin_material_used',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total resin used in ml', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='resin_post_process_time',
            field=models.IntegerField(blank=True, default=30, help_text='Post-processing time in minutes (washing, curing)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='resin_printing_time',
            field=models.IntegerField(blank=True, default=180, help_text='Resin printing time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='resin_setup_time',
            field=models.IntegerField(blank=True, default=5, help_text='Setup time in minutes (minimal for resin)', null=True),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='estimated_price_per_hour',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Estimated hourly rate for this service', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this service is currently offered'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='about_us',
            field=models.TextField(default='We are a cutting-edge manufacturing company...', help_text='About us section content'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_address',
            field=models.TextField(default='123 Main St, City, State, ZIP', help_text='Physical address of the company'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_mission',
            field=models.TextField(default='To provide innovative manufacturing solutions...', help_text='Company mission statement'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_phone',
            field=models.CharField(default='+1-XXX-XXX-XXXX', help_text='Main contact phone for the company', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_tagline',
            field=models.CharField(default='Innovating Manufacturing Solutions', help_text='Company tagline or slogan', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_time_response_hours',
            field=models.IntegerField(default=24, help_text='Standard response time in hours'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_vision',
            field=models.TextField(default='To be the leading provider of digital manufacturing...', help_text='Company vision statement'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='contact_email',
            field=models.EmailField(default='contact@agahsolutions.com', help_text='Main contact email for the company', max_length=254),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='design_file',
            field=models.FileField(blank=True, help_text='Upload design files for the order', null=True, upload_to='order_files/', validators=[services.models.validate_design_file]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='laser_consumables',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, help_text='Cost of consumables (negligible for laser)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='laser_design_programming_time',
            field=models.IntegerField(blank=True, default=15, help_text='Design and programming time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='laser_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Material cost per square inch', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='laser_post_process_time',
            field=models.IntegerField(blank=True, default=3, help_text='Post-processing time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='plasma_consumables',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of consumables (electrodes, nozzles, etc.)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='plasma_cutting_time',
            field=models.IntegerField(blank=True, default=10, help_text='Cutting time in minutes (minimum 10)', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='plasma_design_programming_time',
            field=models.IntegerField(blank=True, default=20, help_text='Design and programming time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='plasma_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Material cost per square inch', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='plasma_post_process_time',
            field=models.IntegerField(blank=True, default=5, help_text='Post-processing time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='description',
            field=models.TextField(help_text='Detailed description of the service'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='image',
            field=models.ImageField(blank=True, help_text='Image representing the service', null=True, upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='name',
            field=models.CharField(help_text='Name of the service type', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='order_display',
            field=models.IntegerField(default=0, help_text='Order in which service appears on website'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='short_description',
            field=models.CharField(help_text='Brief description for cards and previews', max_length=200),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='type',
            field=models.CharField(help_text='Internal type identifier for the service', max_length=50),
        ),
    ]
