# Generated by Django 5.2.4 on 2025-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_typeservice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='laser_consumables',
            field=models.DecimalField(blank=True, decimal_places=2, default=30.0, help_text='Consumables cost (default 30.00)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='laser_cutting_time',
            field=models.IntegerField(blank=True, default=10, help_text='Cutting time in minutes (minimum 10)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='laser_design_programming_time',
            field=models.IntegerField(blank=True, default=30, help_text='Design and programming time in minutes (minimum 30)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='laser_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Material cost for 4'x8' sheet", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='laser_post_process_time',
            field=models.IntegerField(blank=True, default=10, help_text='Post-process time in minutes (minimum 10)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plasma_consumables',
            field=models.DecimalField(blank=True, decimal_places=2, default=162.3, help_text='Consumables cost (default 162.30)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plasma_cutting_time',
            field=models.IntegerField(blank=True, default=30, help_text='Cutting time in minutes (minimum 30)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plasma_design_programming_time',
            field=models.IntegerField(blank=True, default=60, help_text='Design and programming time in minutes (minimum 60)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plasma_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Material cost for 4'x8' plate", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plasma_post_process_time',
            field=models.IntegerField(blank=True, default=60, help_text='Post-process time in minutes (minimum 60)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_consumables',
            field=models.DecimalField(blank=True, decimal_places=2, default=30.0, help_text='Consumables cost (default 30.00)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_design_programming_time',
            field=models.IntegerField(blank=True, default=60, help_text='Design and programming time in minutes (minimum 60)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=350.0, help_text='Material cost per 1Kg roll (default 350.00)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_material_used',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Material used in grams', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_post_process_time',
            field=models.IntegerField(blank=True, default=60, help_text='Post-process time in minutes (minimum 60)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_time',
            field=models.IntegerField(blank=True, default=30, help_text='Printing time in minutes (minimum 30)', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='height_dimensions',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height of the design in inches', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='length_dimensions',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length of the design in inches', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='width_dimensions',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width of the design in inches', max_digits=8, null=True),
        ),
    ]
