# Generated by Django 5.2.4 on 2025-09-04 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_companyconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyconfiguration',
            options={'verbose_name': 'Company Configuration', 'verbose_name_plural': 'Company Configuration'},
        ),
        migrations.AlterModelOptions(
            name='typeservice',
            options={'ordering': ['order_display', 'name'], 'verbose_name': 'Type of Service', 'verbose_name_plural': 'Types of Services'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='laser_material_area_used',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='laser_setup_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='plasma_material_area_used',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='plasma_setup_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_3d_consumables',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_3d_design_programming_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_3d_material_cost',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_3d_material_used',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_3d_post_process_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_3d_printing_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_3d_setup_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='resin_consumables',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='resin_design_programming_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='resin_material_cost',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='resin_material_used',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='resin_post_process_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='resin_printing_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='resin_setup_time',
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='estimated_price_per_hour',
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='is_active',
        ),
        migrations.AddField(
            model_name='companyconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 4, 21, 48, 53, 566855, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_consumables',
            field=models.DecimalField(blank=True, decimal_places=2, default=30.0, help_text='Consumables cost (default 30.00)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_design_programming_time',
            field=models.IntegerField(blank=True, default=60, help_text='Design and programming time in minutes (minimum 60)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=350.0, help_text='Material cost per 1Kg roll (default 350.00)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_material_used',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Material used in grams', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_post_process_time',
            field=models.IntegerField(blank=True, default=60, help_text='Post-process time in minutes (minimum 60)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printing_time',
            field=models.IntegerField(blank=True, default=30, help_text='Printing time in minutes (minimum 30)', null=True),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates if the service is active'),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price for the service', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='is_base_service',
            field=models.BooleanField(default=False, help_text='Indicates if this is one of the 5 base services'),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured services appear prominently'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='about_us',
            field=models.TextField(blank=True, help_text='About us section content'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_address',
            field=models.TextField(blank=True, help_text='Company address'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_mission',
            field=models.TextField(blank=True, help_text='Company mission statement'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_phone',
            field=models.CharField(default='+52 665 127 0811', help_text='Main phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_tagline',
            field=models.CharField(default='Cutting-Edge Solutions, Crafted to Perfection', help_text='Company tagline or slogan', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_time_response_hours',
            field=models.IntegerField(default=24, help_text='Expected response time in hours'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='company_vision',
            field=models.TextField(blank=True, help_text='Company vision statement'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='contact_email',
            field=models.EmailField(default='agahsolutions@gmail.com', help_text='Main contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='laser_consumables',
            field=models.DecimalField(blank=True, decimal_places=2, default=30.0, help_text='Consumables cost (default 30.00)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='laser_design_programming_time',
            field=models.IntegerField(blank=True, default=30, help_text='Design and programming time in minutes (minimum 30)', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='laser_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Material cost', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='laser_post_process_time',
            field=models.IntegerField(blank=True, default=10, help_text='Post-process time in minutes (minimum 10)', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='plasma_consumables',
            field=models.DecimalField(blank=True, decimal_places=2, default=162.3, help_text='Consumables cost (default 162.30)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='plasma_cutting_time',
            field=models.IntegerField(blank=True, default=30, help_text='Cutting time in minutes (minimum 30)', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='plasma_design_programming_time',
            field=models.IntegerField(blank=True, default=60, help_text='Design and programming time in minutes (minimum 60)', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='plasma_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Material cost for 4'x8' plate", max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='plasma_post_process_time',
            field=models.IntegerField(blank=True, default=60, help_text='Post-process time in minutes (minimum 60)', null=True),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the service type'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='image',
            field=models.ImageField(blank=True, help_text='Service image for display', null=True, upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='name',
            field=models.CharField(help_text='Name of the service type', max_length=100),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='order_display',
            field=models.IntegerField(blank=True, help_text='Order for displaying services (auto-assigned)', null=True),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description of the service', max_length=200),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='type',
            field=models.CharField(blank=True, help_text='Type of service offered (auto-generated from name)', max_length=50, unique=True),
        ),
    ]
